#!/usr/bin/env bash
# Display information about subdomains

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n1)
    local record_type=$(echo "$result" | awk '{print $4}')
    local destination=$(echo "$result" | awk '{print $5}')
    
    if [ -n "$destination" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

if [ $# -eq 1 ]; then
    # Display info for default subdomains
    get_subdomain_info "$1" "www"
    get_subdomain_info "$1" "lb-01"
    get_subdomain_info "$1" "web-01"
    get_subdomain_info "$1" "web-02"
elif [ $# -eq 2 ]; then
    # Display info for specific subdomain
    get_subdomain_info "$1" "$2"
fi
